name = "rpt.rs"
source_repo = ""
description = "rpt.rs theme based on hyde"

# If Porting existing theme
[original]
    author =  "mdo"
    url = "http://andhyde.com"
    repo = "http://www.github.com/mdo/hyde"
